### ISSUE TITLE
Trying to add 1-n relation

### ISSUE THREAD

**Issue by matteofabbri** [VictorScherbakov/DataTanker#12]
Trying to add many values on the same key like here 

https://github.com/nam178/FooDB/blob/30826ecfc19ddad7e218489dffaeea9244e46b16/FooCore/Tree.cs#L125

In here: 
https://github.com/VictorScherbakov/DataTanker/blob/1c77b9667433aa929d5b0b925b17830165c34b40/DataTanker/Core/AccessMethods/BPlusTree/BPlusTree.cs#L275

Is it possible ? Any related suggestions ?

**Comment by VictorScherbakov** [comment]
A B-tree allows us to get the exactly one object corresponding to the given key.
A 1 to n relation means that the key has no longer identify a single object.
Looks like contradiction. I know two ways to resolve this:

1. Treat an actual storing object as a linked list. In this case the path in a B-tree leads us to the head of a list. The head refers to the next item and so on... 

2. As it has already done in many RDBMS: use composite key under the hood. We simply concatenate a user provided key with an autoincremented number (physical address or something like that). In the rest we use the B-tree as usual. All we need to do is to hide the real (composite) key from the user and show him only a non-unique key and iterator.

In both cases external interface should be redesigned to provide an iterator instead of a single value.
